name: Build and Deploy Angular
on:
  push:
    branches:
      - main 

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20 # Utilisation d'une version stable récente

      - name: Install dependencies
        run: npm ci

      - name: Build
        # On garde le base-href avec le nom de ton dépôt GitHub
        run: npx ng build --configuration production --base-href /BabyProject/

      - name: Fix 404 for Angular Routing
        # On utilise le chemin exact que tu as identifié
        run: cp dist/baby-project/browser/index.html dist/baby-project/browser/404.html

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist/baby-project/browser
          branch: gh-pages